 @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FailableIntConsumer<Throwable> failableIntConsumer0 = FailableIntConsumer.nop();
      failableIntConsumer0.accept(1);
  }
 @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FailableIntConsumer<Throwable> failableIntConsumer0 = FailableIntConsumer.nop();
      // Undeclared exception!
      try { 
        failableIntConsumer0.andThen((FailableIntConsumer<Throwable>) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }
 @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FailableIntConsumer<Throwable> failableIntConsumer0 = FailableIntConsumer.nop();
      FailableIntConsumer<Throwable> failableIntConsumer1 = failableIntConsumer0.andThen(failableIntConsumer0);
      FailableIntConsumer<Throwable> failableIntConsumer2 = failableIntConsumer0.andThen(failableIntConsumer1);
      ;
}
