/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 11 18:15:21 GMT 2022
 */

package org.apache.commons.jexl3.scripting;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.charset.Charset;
import javax.script.ScriptException;
import org.apache.commons.jexl3.scripting.Main;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Main_ESTest extends Main_ESTest_scaffolding {

 @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[5];
      SystemInUtil.addInputLine("aY#%2{.n/4");
      try { 
        Main.main(stringArray0);
        fail("Expecting exception: IOException");
      } catch(IOException e) {
         //
         // Simulated exception in System.in
         //
         verifyException("org.evosuite.runtime.util.SystemInUtil", e);
      }
  }
 @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Charset charset0 = Charset.defaultCharset();
      try { 
        Main.read(charset0, "");
        fail("Expecting exception: FileNotFoundException");
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }
 @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[1];
      Main.main(stringArray0);
      try { 
        Main.main(stringArray0);
        fail("Expecting exception: ScriptException");
      } catch(ScriptException e) {
         //
         // java.io.IOException: Simulated exception in System.in
         //
         verifyException("org.apache.commons.jexl3.scripting.JexlScriptEngine", e);
      }
  }
 @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      try { 
        Main.main((String[]) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.jexl3.scripting.Main", e);
      }
  }
 @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[12];
      SystemInUtil.addInputLine("");
      try { 
        Main.main(stringArray0);
        fail("Expecting exception: IOException");
      } catch(IOException e) {
         //
         // Simulated exception in System.in
         //
         verifyException("org.evosuite.runtime.util.SystemInUtil", e);
      }
  }
 @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Charset charset0 = Charset.defaultCharset();
      BufferedReader bufferedReader0 = Main.read(charset0, (String) null);
      ;
}
 @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String[] stringArray0 = new String[6];
      Main.main(stringArray0);
      ;
}
 @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "3beHtB&V)";
      try { 
        Main.main(stringArray0);
        fail("Expecting exception: FileNotFoundException");
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }
 @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Main main0 = new Main();
  }
}
